### ISSUE TITLE
Error during load 'eslint.config.js'

### ISSUE THREAD

**Issue by Yehor-Kapranov-GL** [eslint/config-inspector#48] opened 2024-04-25 16:31 UTC
When I trying to run `npx @eslint/config-inspector`
I get an error: `Error: Dynamic require of "fs" is not supported`
Env: Node.js 20
Config
```js
import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
  { languageOptions: { globals: globals.node } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['__tests__/**/*'],
    plugins: ['jest'],
    env: {
      'jest/globals': true,
    },
  },
  {
    rules: {
      'prefer-const': 'error',
      'max-len': ['error', { code: 120, ignoreComments: true }],
    },
    files: ['**/*.ts'],
  },
];
```

**Comment by antfu** [comment] 2024-04-25 17:28
I suppose `plugins: ['jest']` isn't even valid in flat config

**Comment by antfu** [comment] 2024-04-25 17:28
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-25 17:28 UTC

**Comment by Haprog** [comment] 2025-04-15 12:21
Not sure if this is a bug in the config inspector, sheriff or some dependency but I get a similar error:

> ℹ Reading ESLint config from /Users/redacted/vite-project/eslint.config.ts
Failed to load `eslint.config.js`.
Note that `@eslint/config-inspector` only works with the flat config format:
https://eslint.org/docs/latest/use/configure/configuration-files-new
Error: Dynamic require of "eslint/use-at-your-own-risk" is not supported
    at file:///Users/redacted/vite-project/node_modules/.pnpm/eslint-plugin-remeda@1.6.0_eslint@9.24.0_jiti@2.4.2_/node_modules/eslint-plugin-remeda/dist/index.js:11:9
...

This happens in a newly scaffolded vite project with Sheriff and TypeScript.

```shell
# create new vite project
> pnpm create vite
# select Vanilla (no framework)
# cd to new project directory
> pnpm create @sherifforg/config
# select TypeScript
# run config inspector
> pnpm dlx @eslint/config-inspector@latest
```
