### ISSUE TITLE
When soft-linked shared configuration package is used, the message is that the module cannot be found.

### ISSUE THREAD

**Issue by smallmain** [eslint/config-inspector#81] opened 2024-08-07 17:03 UTC
package.json:
```json
  "devDependencies": {
    "eslint-xxx-config": "link:/Users/xxx/config"
  },
```

eslint.config.js in the project:
```js
import { eslint } from "eslint-xxx-config";

export default [...eslint.config];
```

The module imported in the shared configuration package is not found. This problem does not occur if the non-soft link is used.

**Comment by antfu** [comment] 2024-08-12 10:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-12 10:42 UTC
