### ISSUE TITLE
Empty rules shown on configs page (grid layout)

### ISSUE THREAD

**Issue by alexey-koran** [eslint/config-inspector#93] opened 2024-10-03 18:01 UTC
Rules are shown as empty blocks when the layout grid is enabled if there are any unsupported rules (e.g. added by a plugin)

![Image](https://github.com/user-attachments/assets/6525b398-8f6f-48ca-a383-1567165ae966)

If you add [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#configuration-new-eslintconfigjs) which includes [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/blob/main/eslint.base.config.js) rules related to `vue`, `flowtype` & etc.

Func `getRuleFromName` returns undefined as the payload has no such rules

https://github.com/eslint/config-inspector/blob/27654d5f0f24b491b346fb921de25da9e2c3e956/app/components/RuleList.vue#L15-L19

https://github.com/eslint/config-inspector/blob/27654d5f0f24b491b346fb921de25da9e2c3e956/app/composables/payload.ts#L89-L92

Maybe it's worth checking if the rule exists in the payload?

**Comment by antfu** [comment] 2024-10-05 03:44
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-10-05 03:44 UTC
