### ISSUE TITLE
No ESLint configuration file was found.

### ISSUE THREAD

**Issue by parth391** [eslint/config-inspector#100] opened 2024-10-23 07:56 UTC
`eslint.config.mts` configuration file is not detecting.

    You can also run this command directly using 'npx @eslint/config-inspector@latest' in the same directory as your configuration file.
    Error: No ESLint configuration file was found.
        at locateConfigFileToUse (/node_modules/eslint/lib/eslint/eslint.js:284:15)
        at async Object.calculateInspectConfigFlags (/node_modules/eslint/lib/cli.js:353:13)
        at async Object.execute (/node_modules/eslint/lib/cli.js:454:31)
        at async main (/node_modules/eslint/bin/eslint.js:158:22)

**Comment by antfu** [comment] 2024-10-24 15:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-10-24 15:42 UTC
